export default [
    "../themes/SPRUCE",
    "../themes/2021 Stock by Miyoo",
    "../themes/2022 Stock by Miyoo",
    "../themes/2CleanMini by Sheezie",
    "../themes/3DS mini by MarsTaco",
    "../themes/999-in-1 by UnBurn",
    "../themes/A Link to the Past by tendo209",
    "../themes/AmalgaM by ZaxxonQ",
    "../themes/AnalogPhosphor (3-pack) by trash/AnalogPhosphor by trash",
    "../themes/AnalogPhosphor (3-pack) by trash/AnalogPhosphor Alt by trash",
    "../themes/AnalogPhosphor (3-pack) by trash/AnalogPhosphorOG by trash",
    "../themes/Analogue Blanche by Aemiii91",
    "../themes/Analogue by Aemiii91",
    "../themes/Animiyoo by laumser7",
    "../themes/Aubergine by blueasis",
    "../themes/Bayonetta by Kryobear",
    "../themes/Beneath The Mask by UnBurn",
    "../themes/BirdShot by historymaker118",
    "../themes/Black Cotton Candy by PixelShift",
    "../themes/Blank Space by ElectRefurbish",
    "../themes/Blank Space Inverted by ElectRefurbish",
    "../themes/Blueprint by Aemiii91",
    "../themes/Blueprint Ghosts by Aemiii91 + ax2far/Blueprint Ghosts Basic by Aemiii91 + ax2far",
    "../themes/Blueprint Ghosts by Aemiii91 + ax2far/Blueprint Ghosts by Aemiii91 + ax2far",
    "../themes/Blueprint Variations by Aemiii91 + r3b0rn/Blueprint BLACK by Aemiii91 + r3b0rn",
    "../themes/Blueprint Variations by Aemiii91 + r3b0rn/Blueprint PURPLE by Aemiii91 + r3b0rn",
    "../themes/Blueprint Variations by Aemiii91 + r3b0rn/Blueprint REVERSO by Aemiii91 + r3b0rn",
    "../themes/BMO by OjninJo",
    "../themes/BRCKD by Deepslackerjazz",
    "../themes/Business by Jim Gray",
    "../themes/Capcom SNK (Handheld Filter) by Sheezie",
    "../themes/Cards by PixelShift",
    "../themes/CastlevaniaSOTN by RoeTaKa",
    "../themes/Cave+ by apg313",
    "../themes/ChronoMi by apg313",
    "../themes/Classic TV by RetroReef",
    "../themes/CleanOnionGB by KulhyCZ",
    "../themes/Codec by ScarGutz",
    "../themes/Concise (3-pack) by mtaras/Concise Black White by mtaras",
    "../themes/Concise (3-pack) by mtaras/Concise Light Purple by mtaras",
    "../themes/Concise (3-pack) by mtaras/Concise Dark Teal by mtaras",
    "../themes/Contra Miyoo by tenlevels",
    "../themes/Cosy by KyleBing",
    "../themes/CyberOnion (2-pack) by Aemiii91/CyberOnion by Aemiii91",
    "../themes/CyberOnion (2-pack) by Aemiii91/CyberOnion [Atomic] by Aemiii91",
    "../themes/Cyberpunk by Dreams897",
    "../themes/Dark Onion by Alpatov Danila",
    "../themes/Def not SFC - Dark by Danilo Colasso",
    "../themes/Def not SFC by Danilo Colasso",
    "../themes/Def not SNES by Danilo Colasso",
    "../themes/DNTSHP by Deepslackerjazz",
    "../themes/Dragon Ball Mini by UnBurn",
    "../themes/DS XS by UnBurn",
    "../themes/End of Ages by apg313",
    "../themes/EVA by laumser7 + trere",
    "../themes/Fairy-Type by UnBurn",
    "../themes/Fake DMG Classic by Oclain",
    "../themes/Fake Pocket by Oclain",
    "../themes/FireMiyoo by Isocron",
    "../themes/Fuzzy Pickles! by Updog",
    "../themes/Galaxy by PixelShift",
    "../themes/Game Boy Scouts by UnBurn",
    "../themes/GameMaster",
    "../themes/GBC Pokedex by Nxt.stop.please",
    "../themes/GBMini by Kitsuvi",
    "../themes/GBOnion by Kitsuvi",
    "../themes/GBOnion Dark by Kitsuvi + andresandiah",
    "../themes/GBOnion Gruvbox by Kitsuvi + Dreambrace",
    "../themes/gry64 by iamatrap",
    "../themes/Hallownest by Myth + Solsta",
    "../themes/HAZARD by Dreambrace",
    "../themes/Hello Miyoo by tenlevels",
    "../themes/Hippo Stock",
    "../themes/Hyrule Dark by ruidacosta",
    "../themes/Impact by edvardeishen",
    "../themes/KantOS by antonlabz",
    "../themes/Kingdom Onions by PixelShift",
    "../themes/klar (8-pack) by m_axic/klar lime by m_axic",
    "../themes/klar (8-pack) by m_axic/klar sand by m_axic",
    "../themes/klar (8-pack) by m_axic/klar berry by m_axic",
    "../themes/klar (8-pack) by m_axic/klar crimson by m_axic",
    "../themes/klar (8-pack) by m_axic/klar snow by m_axic",
    "../themes/klar (8-pack) by m_axic/klar honey by m_axic",
    "../themes/klar (8-pack) by m_axic/klar coal by m_axic",
    "../themes/klar (8-pack) by m_axic/klar aqua by m_axic",
    "../themes/less by junk",
    "../themes/Lifestream by Inheritor",
    "../themes/Lilla by evolve",
    "../themes/Lylat System by UnBurn",
    "../themes/M by tenlevels",
    "../themes/MajoraMi by apg313",
    "../themes/MakoVII by Gloomy_Background755",
    "../themes/MasterHacker by Squ1d0ne",
    "../themes/Material (6-pack) by tenlevels/Material Blue by tenlevels",
    "../themes/Material (6-pack) by tenlevels/Material Orange by tenlevels",
    "../themes/Material (6-pack) by tenlevels/Material Pink by tenlevels",
    "../themes/Material (6-pack) by tenlevels/Material Purple by tenlevels",
    "../themes/Material (6-pack) by tenlevels/Material Green by tenlevels",
    "../themes/Material (6-pack) by tenlevels/Material White by tenlevels",
    "../themes/MegaManX by NoLetterhead485",
    "../themes/Milk Black by Segich + Nemi",
    "../themes/Milk White by Segich",
    "../themes/mini.os by nationalsoup",
    "../themes/minimO by AccomplishedSir",
    "../themes/MiNook Mini by Deepslackerjazz",
    "../themes/Miyoo blues",
    "../themes/Miyoo jazz",
    "../themes/Miyoo Quest by y_oshid_a",
    "../themes/Miyoo Slug by tenlevels",
    "../themes/Miyoo Truxton by tenlevels",
    "../themes/Miyoo Valley (2-pack) by dragon-fruity/Miyoo Valley Xmas by dragon-fruity",
    "../themes/Miyoo Valley (2-pack) by dragon-fruity/Miyoo Valley by dragon-fruity",
    "../themes/Miyoo x Rilakkuma Pink! by Jasminum C",
    "../themes/MiyooCarPlay by RobyRosa",
    "../themes/M-NOIR by tenlevels",
    "../themes/Monster Hunter by Miyoo",
    "../themes/Mucha Miyoo by LamiaLazuli",
    "../themes/NanoSwitch (2-pack) by Amdy/NanoSwitch Dark by Amdy",
    "../themes/NanoSwitch (2-pack) by Amdy/NanoSwitch by Amdy",
    "../themes/NanoSwitch Modern Dark by Amdy + Cheetashock",
    "../themes/National Pokedex by Vanta_black",
    "../themes/NBA Onion by Tom Tower",
    "../themes/NEO GEO by tenlevels",
    "../themes/NEON.ion by tenlevels",
    "../themes/NES by MLOPEZMAD",
    "../themes/Neumorphism (3-pack) by bantam/Neumorphism-Yellow by bantam",
    "../themes/Neumorphism (3-pack) by bantam/Neumorphism-White by bantam",
    "../themes/Neumorphism (3-pack) by bantam/Neumorphism-Black by bantam",
    "../themes/Nokiyoo by UnBurn",
    "../themes/Notebook Kawaii by UnBurn",
    "../themes/Onichan by PixelShift",
    "../themes/Onion Blocks (2-pack) by tenlevels/Onion Blocks Sequential",
    "../themes/Onion Blocks (2-pack) by tenlevels/Onion Blocks Concurrent",
    "../themes/Onion Boy by PixelShift + Jeltron",
    "../themes/Onion Boy Dark by PixelShift",
    "../themes/Onion Boy DX by PixelShift",
    "../themes/Onion Boy HD SP by Jeltron + Smushi",
    "../themes/Onion Boy Pocket by PixelShift + H9K",
    "../themes/Onion Mini by Jeltron",
    "../themes/ONION PS (4-pack) by hanessh4/ONION PS Dark Blue by hanessh4",
    "../themes/ONION PS (4-pack) by hanessh4/ONION PS Dark Grey by hanessh4",
    "../themes/ONION PS (4-pack) by hanessh4/ONION PS Purple Grey by hanessh4",
    "../themes/ONION PS (4-pack) by hanessh4/ONION PS Blue by hanessh4",
    "../themes/ONION Simpson by Polpetta",
    "../themes/Onionboy HD by Jeltron",
    "../themes/Onionboy HD Gray by Jeltron + TechDevangelist",
    "../themes/Onyan by PixelShift",
    "../themes/OOSFC by ytdcpndsgn",
    "../themes/Oransje by evolve",
    "../themes/Original by SandsByte",
    "../themes/OSRS Theme by Mahan",
    "../themes/PAC-MIYOO by tenlevels",
    "../themes/Pad (4-pack) by toski/Pad Neon Sky by toski",
    "../themes/Pad (4-pack) by toski/Pad Retro Peach by toski",
    "../themes/Pad (4-pack) by toski/Pad Snow Dark by toski",
    "../themes/Pad (4-pack) by toski/Pad Retro Orchid by toski",
    "../themes/PICO-8 (3-pack) by tenlevels/PICO-FANTASY by tenlevels",
    "../themes/PICO-8 (3-pack) by tenlevels/PICO-NIGHT SKY by tenlevels",
    "../themes/PICO-8 (3-pack) by tenlevels/PICO-DEV by tenlevels",
    "../themes/Pikachu Edition by UnBurn",
    "../themes/PIXELPUNK by anthr_alxndr",
    "../themes/Plastic Leaf (EU) by leafflat",
    "../themes/Plastic Leaf (NA) by leafflat",
    "../themes/Pocket Gank by UnBurn",
    "../themes/PocketFighterMini by nGlory",
    "../themes/Pokemon Mystery Dungeon by Sheezie",
    "../themes/Poketch by Lucario",
    "../themes/Power Onions OS by LeonardoDaPinchy",
    "../themes/PPLP by Deepslackerjazz",
    "../themes/PSPmini Blue by MarsTaco",
    "../themes/PSPmini by MarsTaco",
    "../themes/PSX Theme by Oclain",
    "../themes/Red Onion by PixelShift + Jeltron + Moontorc",
    "../themes/RETRONION by MLOPEZMAD",
    "../themes/RetroRama by TooGeekCreations",
    "../themes/Rick and Morty Mini by Zooloo631",
    "../themes/RPO by TheDewd",
    "../themes/Shadaloo (SFA3) by XCVNCE",
    "../themes/Shallot by Cyberbellum",
    "../themes/sharp by m_axic",
    "../themes/Silky by DiMo",
    "../themes/Silky Remix SUPER GAME BOY by MLOPEZMAD",
    "../themes/Simple Pixels (2-pack) by Cuprite/Simple Pixels Color by Cuprite",
    "../themes/Simple Pixels (2-pack) by Cuprite/Simple Pixels BW by Cuprite",
    "../themes/Sonic (2-pack) by tenlevels/Sonic Theme B by tenlevels",
    "../themes/Sonic (2-pack) by tenlevels/Sonic Theme A by tenlevels",
    "../themes/Sonic Origins by Sheezie",
    "../themes/sONIONc by tenlevels",
    "../themes/Spider-Miyoo by ElectRefurbish",
    "../themes/Sprite Buddies LucasArts by ShrimpFandangle",
    "../themes/Sprite Buddies NES by ShrimpFandangle",
    "../themes/Sprite Buddies SNES by ShrimpFandangle",
    "../themes/Star Wars (Miyoo Be With You) by tenlevels",
    "../themes/StarOnion64 by LeonardoDaPinchy",
    "../themes/SUPER GAME BOY by MLOPEZMAD",
    "../themes/Super Mariyoo by tenlevels",
    "../themes/Super Onion Entertainment System by TheDewd",
    "../themes/Super Onion Entertainment System Remix by TheDewd + Quack Walks",
    "../themes/Switch by PixelShift",
    "../themes/Synthwave by Ritual",
    "../themes/System 9 by injekim",
    "../themes/TechDweeb by TechDweeb",
    "../themes/Tema by Alex Connor",
    "../themes/THPS2 by tenlevels",
    "../themes/TMNT by RealDan",
    "../themes/TOTK by NaraMakesGames",
    "../themes/TrimUI by Aemiii91",
    "../themes/TRON by tenlevels",
    "../themes/TTYD by Kryobear",
    "../themes/Ultralight by parkinglotmusic",
    "../themes/Valorant by Skimpertushi",
    "../themes/VII by Moowgly",
    "../themes/vintage_aesthe by uchebo_bro",
    "../themes/Wasteland by Bernig",
    "../themes/Wasteland Nevada by Bernig + LeonardoDaPinchy",
    "../themes/Wavedash by historymaker118",
    "../themes/Wiiyoo by UnBurn",
    "../themes/win98 by kyhynngy_oyuur",
    "../themes/Wireframe by KyleBing",
    "../themes/YoRHa by Deepslackerjazz",
    "../themes/Zelda Oracle by Slak211",
    "../themes/Zenburn 1.5 by duckbeets + Catz",
    "../themes/Zenburn by duckbeets",
    "../themes/Zigzag-iyoo-n Mini (2-pack) by Cuprite/Zigzag-iyoo-n Rainbow by Cuprite",
    "../themes/Zigzag-iyoo-n Mini (2-pack) by Cuprite/Zigzag-iyoo-n Mini by Cuprite",
]
